[package]
name = "params_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_retrieve = {path="../data_retrieve"}
tsa_sim = {path="../tsa_sim"}

threadpool = "1.8.1"
