[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsa_sim = {path="../tsa_sim"}
graphics_engine = {path="../graphics_engine"}
data_retrieve = {path="../data_retrieve"}
