[package]
name = "tsa_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_retrieve = {path="../data_retrieve"}
rand = "0.8.5"
